/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecompensaRouteImport } from './routes/recompensa'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as HubRouteImport } from './routes/hub'
import { Route as CuentaRouteImport } from './routes/cuenta'
import { Route as CrearAvatarRouteImport } from './routes/crear-avatar'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BibliotecaIndexRouteImport } from './routes/biblioteca.index'
import { Route as RetoPuzzleRouteImport } from './routes/reto.puzzle'
import { Route as RetoPuentesRouteImport } from './routes/reto.puentes'
import { Route as RetoEcuacionesRouteImport } from './routes/reto.ecuaciones'
import { Route as RetoDueloRouteImport } from './routes/reto.duelo'
import { Route as RetoCartasRouteImport } from './routes/reto.cartas'
import { Route as RetoBossRouteImport } from './routes/reto.boss'
import { Route as RetoArenaRouteImport } from './routes/reto.arena'
import { Route as MundoBosqueRouteImport } from './routes/mundo.bosque'
import { Route as MundoAlgoritmosRouteImport } from './routes/mundo.algoritmos'
import { Route as MundoWorldIdRouteImport } from './routes/mundo.$worldId'
import { Route as BibliotecaAventuraDocIdRouteImport } from './routes/biblioteca.aventura.$docId'
import { Route as BibliotecaAnalizandoDocIdRouteImport } from './routes/biblioteca.analizando.$docId'

const RecompensaRoute = RecompensaRouteImport.update({
  id: '/recompensa',
  path: '/recompensa',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRoute = CuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const CrearAvatarRoute = CrearAvatarRouteImport.update({
  id: '/crear-avatar',
  path: '/crear-avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaIndexRoute = BibliotecaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BibliotecaRoute,
} as any)
const RetoPuzzleRoute = RetoPuzzleRouteImport.update({
  id: '/reto/puzzle',
  path: '/reto/puzzle',
  getParentRoute: () => rootRouteImport,
} as any)
const RetoPuentesRoute = RetoPuentesRouteImport.update({
  id: '/reto/puentes',
  path: '/reto/puentes',
  getParentRoute: () => rootRouteImport,
} as any)
const RetoEcuacionesRoute = RetoEcuacionesRouteImport.update({
  id: '/reto/ecuaciones',
  path: '/reto/ecuaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const RetoDueloRoute = RetoDueloRouteImport.update({
  id: '/reto/duelo',
  path: '/reto/duelo',
  getParentRoute: () => rootRouteImport,
} as any)
const RetoCartasRoute = RetoCartasRouteImport.update({
  id: '/reto/cartas',
  path: '/reto/cartas',
  getParentRoute: () => rootRouteImport,
} as any)
const RetoBossRoute = RetoBossRouteImport.update({
  id: '/reto/boss',
  path: '/reto/boss',
  getParentRoute: () => rootRouteImport,
} as any)
const RetoArenaRoute = RetoArenaRouteImport.update({
  id: '/reto/arena',
  path: '/reto/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const MundoBosqueRoute = MundoBosqueRouteImport.update({
  id: '/mundo/bosque',
  path: '/mundo/bosque',
  getParentRoute: () => rootRouteImport,
} as any)
const MundoAlgoritmosRoute = MundoAlgoritmosRouteImport.update({
  id: '/mundo/algoritmos',
  path: '/mundo/algoritmos',
  getParentRoute: () => rootRouteImport,
} as any)
const MundoWorldIdRoute = MundoWorldIdRouteImport.update({
  id: '/mundo/$worldId',
  path: '/mundo/$worldId',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaAventuraDocIdRoute = BibliotecaAventuraDocIdRouteImport.update({
  id: '/aventura/$docId',
  path: '/aventura/$docId',
  getParentRoute: () => BibliotecaRoute,
} as any)
const BibliotecaAnalizandoDocIdRoute =
  BibliotecaAnalizandoDocIdRouteImport.update({
    id: '/analizando/$docId',
    path: '/analizando/$docId',
    getParentRoute: () => BibliotecaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/crear-avatar': typeof CrearAvatarRoute
  '/cuenta': typeof CuentaRoute
  '/hub': typeof HubRoute
  '/mapa': typeof MapaRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/recompensa': typeof RecompensaRoute
  '/mundo/$worldId': typeof MundoWorldIdRoute
  '/mundo/algoritmos': typeof MundoAlgoritmosRoute
  '/mundo/bosque': typeof MundoBosqueRoute
  '/reto/arena': typeof RetoArenaRoute
  '/reto/boss': typeof RetoBossRoute
  '/reto/cartas': typeof RetoCartasRoute
  '/reto/duelo': typeof RetoDueloRoute
  '/reto/ecuaciones': typeof RetoEcuacionesRoute
  '/reto/puentes': typeof RetoPuentesRoute
  '/reto/puzzle': typeof RetoPuzzleRoute
  '/biblioteca/': typeof BibliotecaIndexRoute
  '/biblioteca/analizando/$docId': typeof BibliotecaAnalizandoDocIdRoute
  '/biblioteca/aventura/$docId': typeof BibliotecaAventuraDocIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/crear-avatar': typeof CrearAvatarRoute
  '/cuenta': typeof CuentaRoute
  '/hub': typeof HubRoute
  '/mapa': typeof MapaRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/recompensa': typeof RecompensaRoute
  '/mundo/$worldId': typeof MundoWorldIdRoute
  '/mundo/algoritmos': typeof MundoAlgoritmosRoute
  '/mundo/bosque': typeof MundoBosqueRoute
  '/reto/arena': typeof RetoArenaRoute
  '/reto/boss': typeof RetoBossRoute
  '/reto/cartas': typeof RetoCartasRoute
  '/reto/duelo': typeof RetoDueloRoute
  '/reto/ecuaciones': typeof RetoEcuacionesRoute
  '/reto/puentes': typeof RetoPuentesRoute
  '/reto/puzzle': typeof RetoPuzzleRoute
  '/biblioteca': typeof BibliotecaIndexRoute
  '/biblioteca/analizando/$docId': typeof BibliotecaAnalizandoDocIdRoute
  '/biblioteca/aventura/$docId': typeof BibliotecaAventuraDocIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/crear-avatar': typeof CrearAvatarRoute
  '/cuenta': typeof CuentaRoute
  '/hub': typeof HubRoute
  '/mapa': typeof MapaRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/recompensa': typeof RecompensaRoute
  '/mundo/$worldId': typeof MundoWorldIdRoute
  '/mundo/algoritmos': typeof MundoAlgoritmosRoute
  '/mundo/bosque': typeof MundoBosqueRoute
  '/reto/arena': typeof RetoArenaRoute
  '/reto/boss': typeof RetoBossRoute
  '/reto/cartas': typeof RetoCartasRoute
  '/reto/duelo': typeof RetoDueloRoute
  '/reto/ecuaciones': typeof RetoEcuacionesRoute
  '/reto/puentes': typeof RetoPuentesRoute
  '/reto/puzzle': typeof RetoPuzzleRoute
  '/biblioteca/': typeof BibliotecaIndexRoute
  '/biblioteca/analizando/$docId': typeof BibliotecaAnalizandoDocIdRoute
  '/biblioteca/aventura/$docId': typeof BibliotecaAventuraDocIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/crear-avatar'
    | '/cuenta'
    | '/hub'
    | '/mapa'
    | '/perfil'
    | '/ranking'
    | '/recompensa'
    | '/mundo/$worldId'
    | '/mundo/algoritmos'
    | '/mundo/bosque'
    | '/reto/arena'
    | '/reto/boss'
    | '/reto/cartas'
    | '/reto/duelo'
    | '/reto/ecuaciones'
    | '/reto/puentes'
    | '/reto/puzzle'
    | '/biblioteca/'
    | '/biblioteca/analizando/$docId'
    | '/biblioteca/aventura/$docId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/crear-avatar'
    | '/cuenta'
    | '/hub'
    | '/mapa'
    | '/perfil'
    | '/ranking'
    | '/recompensa'
    | '/mundo/$worldId'
    | '/mundo/algoritmos'
    | '/mundo/bosque'
    | '/reto/arena'
    | '/reto/boss'
    | '/reto/cartas'
    | '/reto/duelo'
    | '/reto/ecuaciones'
    | '/reto/puentes'
    | '/reto/puzzle'
    | '/biblioteca'
    | '/biblioteca/analizando/$docId'
    | '/biblioteca/aventura/$docId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/crear-avatar'
    | '/cuenta'
    | '/hub'
    | '/mapa'
    | '/perfil'
    | '/ranking'
    | '/recompensa'
    | '/mundo/$worldId'
    | '/mundo/algoritmos'
    | '/mundo/bosque'
    | '/reto/arena'
    | '/reto/boss'
    | '/reto/cartas'
    | '/reto/duelo'
    | '/reto/ecuaciones'
    | '/reto/puentes'
    | '/reto/puzzle'
    | '/biblioteca/'
    | '/biblioteca/analizando/$docId'
    | '/biblioteca/aventura/$docId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BibliotecaRoute: typeof BibliotecaRouteWithChildren
  CrearAvatarRoute: typeof CrearAvatarRoute
  CuentaRoute: typeof CuentaRoute
  HubRoute: typeof HubRoute
  MapaRoute: typeof MapaRoute
  PerfilRoute: typeof PerfilRoute
  RankingRoute: typeof RankingRoute
  RecompensaRoute: typeof RecompensaRoute
  MundoWorldIdRoute: typeof MundoWorldIdRoute
  MundoAlgoritmosRoute: typeof MundoAlgoritmosRoute
  MundoBosqueRoute: typeof MundoBosqueRoute
  RetoArenaRoute: typeof RetoArenaRoute
  RetoBossRoute: typeof RetoBossRoute
  RetoCartasRoute: typeof RetoCartasRoute
  RetoDueloRoute: typeof RetoDueloRoute
  RetoEcuacionesRoute: typeof RetoEcuacionesRoute
  RetoPuentesRoute: typeof RetoPuentesRoute
  RetoPuzzleRoute: typeof RetoPuzzleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recompensa': {
      id: '/recompensa'
      path: '/recompensa'
      fullPath: '/recompensa'
      preLoaderRoute: typeof RecompensaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta': {
      id: '/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof CuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crear-avatar': {
      id: '/crear-avatar'
      path: '/crear-avatar'
      fullPath: '/crear-avatar'
      preLoaderRoute: typeof CrearAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca/': {
      id: '/biblioteca/'
      path: '/'
      fullPath: '/biblioteca/'
      preLoaderRoute: typeof BibliotecaIndexRouteImport
      parentRoute: typeof BibliotecaRoute
    }
    '/reto/puzzle': {
      id: '/reto/puzzle'
      path: '/reto/puzzle'
      fullPath: '/reto/puzzle'
      preLoaderRoute: typeof RetoPuzzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reto/puentes': {
      id: '/reto/puentes'
      path: '/reto/puentes'
      fullPath: '/reto/puentes'
      preLoaderRoute: typeof RetoPuentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reto/ecuaciones': {
      id: '/reto/ecuaciones'
      path: '/reto/ecuaciones'
      fullPath: '/reto/ecuaciones'
      preLoaderRoute: typeof RetoEcuacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reto/duelo': {
      id: '/reto/duelo'
      path: '/reto/duelo'
      fullPath: '/reto/duelo'
      preLoaderRoute: typeof RetoDueloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reto/cartas': {
      id: '/reto/cartas'
      path: '/reto/cartas'
      fullPath: '/reto/cartas'
      preLoaderRoute: typeof RetoCartasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reto/boss': {
      id: '/reto/boss'
      path: '/reto/boss'
      fullPath: '/reto/boss'
      preLoaderRoute: typeof RetoBossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reto/arena': {
      id: '/reto/arena'
      path: '/reto/arena'
      fullPath: '/reto/arena'
      preLoaderRoute: typeof RetoArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mundo/bosque': {
      id: '/mundo/bosque'
      path: '/mundo/bosque'
      fullPath: '/mundo/bosque'
      preLoaderRoute: typeof MundoBosqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mundo/algoritmos': {
      id: '/mundo/algoritmos'
      path: '/mundo/algoritmos'
      fullPath: '/mundo/algoritmos'
      preLoaderRoute: typeof MundoAlgoritmosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mundo/$worldId': {
      id: '/mundo/$worldId'
      path: '/mundo/$worldId'
      fullPath: '/mundo/$worldId'
      preLoaderRoute: typeof MundoWorldIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca/aventura/$docId': {
      id: '/biblioteca/aventura/$docId'
      path: '/aventura/$docId'
      fullPath: '/biblioteca/aventura/$docId'
      preLoaderRoute: typeof BibliotecaAventuraDocIdRouteImport
      parentRoute: typeof BibliotecaRoute
    }
    '/biblioteca/analizando/$docId': {
      id: '/biblioteca/analizando/$docId'
      path: '/analizando/$docId'
      fullPath: '/biblioteca/analizando/$docId'
      preLoaderRoute: typeof BibliotecaAnalizandoDocIdRouteImport
      parentRoute: typeof BibliotecaRoute
    }
  }
}

interface BibliotecaRouteChildren {
  BibliotecaIndexRoute: typeof BibliotecaIndexRoute
  BibliotecaAnalizandoDocIdRoute: typeof BibliotecaAnalizandoDocIdRoute
  BibliotecaAventuraDocIdRoute: typeof BibliotecaAventuraDocIdRoute
}

const BibliotecaRouteChildren: BibliotecaRouteChildren = {
  BibliotecaIndexRoute: BibliotecaIndexRoute,
  BibliotecaAnalizandoDocIdRoute: BibliotecaAnalizandoDocIdRoute,
  BibliotecaAventuraDocIdRoute: BibliotecaAventuraDocIdRoute,
}

const BibliotecaRouteWithChildren = BibliotecaRoute._addFileChildren(
  BibliotecaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BibliotecaRoute: BibliotecaRouteWithChildren,
  CrearAvatarRoute: CrearAvatarRoute,
  CuentaRoute: CuentaRoute,
  HubRoute: HubRoute,
  MapaRoute: MapaRoute,
  PerfilRoute: PerfilRoute,
  RankingRoute: RankingRoute,
  RecompensaRoute: RecompensaRoute,
  MundoWorldIdRoute: MundoWorldIdRoute,
  MundoAlgoritmosRoute: MundoAlgoritmosRoute,
  MundoBosqueRoute: MundoBosqueRoute,
  RetoArenaRoute: RetoArenaRoute,
  RetoBossRoute: RetoBossRoute,
  RetoCartasRoute: RetoCartasRoute,
  RetoDueloRoute: RetoDueloRoute,
  RetoEcuacionesRoute: RetoEcuacionesRoute,
  RetoPuentesRoute: RetoPuentesRoute,
  RetoPuzzleRoute: RetoPuzzleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
