// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


/** Error uniforme que devuelve el cliente inerte (nunca lanza). */
const ERROR_INERTE = {
  message: 'Supabase no configurado: el juego funciona en modo local.',
  name: 'SupabaseNoConfigurado',
};

/**
 * Cliente inerte: misma forma que el real para la superficie que usa la app,
 * pero sin red y sin excepciones. Toda operación resuelve `{ data, error }`
 * con `error` presente, que es exactamente lo que los llamadores ya manejan
 * (playerSync ignora el error y sigue con el estado local).
 */
function createClienteInerte() {
  const resultado = async () => ({ data: null, error: ERROR_INERTE });

  // Cadena de consulta encadenable: .from().select().eq().maybeSingle()… y
  // además "thenable", para que un `await` directo también resuelva.
  const cadena: any = new Proxy(
    {},
    {
      get(_t, prop) {
        if (prop === 'then') {
          // Await sobre la cadena → { data: null, error }.
          return (resolve: (v: unknown) => unknown) => resolve({ data: null, error: ERROR_INERTE });
        }
        return () => cadena;
      },
    },
  );

  return {
    auth: {
      getSession: async () => ({ data: { session: null }, error: null }),
      getUser: async () => ({ data: { user: null }, error: null }),
      onAuthStateChange: () => ({
        data: { subscription: { unsubscribe: () => {} } },
      }),
      signInWithOtp: resultado,
      signInWithPassword: resultado,
      signInWithOAuth: resultado,
      signUp: resultado,
      verifyOtp: resultado,
      signOut: async () => ({ error: null }),
    },
    from: () => cadena,
    storage: { from: () => ({ upload: resultado, remove: resultado, download: resultado }) },
    functions: { invoke: resultado },
    channel: () => ({ on: () => ({ subscribe: () => ({ unsubscribe: () => {} }) }), subscribe: () => ({ unsubscribe: () => {} }) }),
    removeChannel: () => {},
  } as unknown as ReturnType<typeof createClient<Database>>;
}

/** true solo si hay credenciales reales (la UI puede ocultar cuenta/ranking). */
export const isSupabaseConfigured: boolean = Boolean(
  (import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL) &&
    (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY),
);

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    // Sin backend configurado el juego DEBE seguir siendo jugable: todo el
    // núcleo (mundos 3D, temario del alumno, retos, progreso) vive en el
    // dispositivo. Devolvemos un cliente inerte en vez de lanzar, para que un
    // despliegue público sin Supabase no muera en el arranque (bootstrapAuth).
    console.warn(
      '[Supabase] Sin configurar (faltan SUPABASE_URL / SUPABASE_PUBLISHABLE_KEY). ' +
        'Modo local: el juego funciona, pero sin cuenta, ranking en la nube ni copia de seguridad.',
    );
    return createClienteInerte();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

